### ISSUE TITLE
gradlew build fails on compileThrift task

### ISSUE THREAD

**Issue by daric93** [uber/cadence-java-client#491]
Error message:
```
> Task :compileThrift FAILED
Could not find /Users/myuser/Workspace/cadence/cadence-java-client/src/main/thrift. Will ignore it
[FAILURE:arguments:1] Could not open input file with realpath: /Users/myuser/.gradle/daemon/6.0/src/main/idls/thrift/cadence.thrift
```

**Comment by mindaugasbarcauskas** [comment]
Not necessarily related since this might have been a code issue but in general:

Please make sure you have the correct thrift version (0.9.3) installed and running

thrift --version

returns correct version.

At least I had to restart my mac after installing thrift for gradle to pick it up correctly.
